cluster_name: stats-collection-{{partition_canonical_string}}-{{trace_id}}

provider:
  type: aws
  region: us-east-1
  availability_zone: us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f
  cache_stopped_nodes: false
  use_internal_ips: true

max_workers: '{{max-workers}}'

auth:
  ssh_user: ubuntu
  ssh_private_key: /tmp/.ssh/metastats-test.pem

available_node_types:
  ray.head.default:
    max_workers: 0
    resources: {}
    node_config:
      InstanceType: '{{head-instance-type}}'
      ImageId: ami-0343983f3bcafa976 # andes-amzn-ray, us-east-1, ray 1.9.2
      KeyName: metastats-test
      LaunchTemplate:
        # TODO: replace this with your launch template name!
        LaunchTemplateName: AlphaRayClusterLaunchTemplateCDK
        Version: "$Latest"
  ray.worker.default:
    min_workers: '{{min-workers}}'
    max_workers: '{{max-workers}}'
    resources: {}
    node_config:
      InstanceType: '{{worker-instance-type}}'
      ImageId: ami-0343983f3bcafa976 # andes-amzn-ray, us-east-1, ray 1.9.2
      KeyName: metastats-test
      LaunchTemplate:
        # TODO: replace this with your launch template name!
        LaunchTemplateName: AlphaRayClusterLaunchTemplateCDK
        Version: "$Latest"
head_node_type: ray.head.default

file_mounts: {
    "~/deltacat/deltacat-0.1.0-py3-none-any.whl": "~/deltacat/deltacat-0.1.0-py3-none-any.whl",
    "/tmp/.ssh/metastats-test.pem": "/tmp/.ssh/metastats-test.pem"
}
setup_commands:
  - rm -f ~/deltacat-0.1.0-py3-none-any.whl
  - pip uninstall -y deltacat
  - pip install ~/deltacat/deltacat-0.1.0-py3-none-any.whl
  - pip uninstall -y amzn-ray
  - pip uninstall -y ray
  - pip install ray[all]==1.13.0
  - chmod 400 /tmp/.ssh/metastats-test.pem
